### ISSUE TITLE
For loop looping forever in forest.go

### ISSUE THREAD

**Issue by kcalvinalvin** [mit-dci/utreexo#65] opened 2020-01-22 07:49 UTC
https://github.com/mit-dci/utreexo/blob/d9ab388431f0e04662dfffe481ba7cf9a6d32c36/utreexo/forest.go#L122

On block 16348 (testnet3), this loops forever. Not quite sure what's going on.

**Comment by adiabat** [comment] 2020-01-22 14:26
Yup, I reproduced this bug.  Weird.  It's not actually looping forever in that it gets to h=0, h=1, and then stops at h=1 with 0% CPU usage.  Will figure this one out... huh.

**Comment by adiabat** [comment] 2020-01-22 14:35
also ctrl-c doesn't work and neither does killall... have to do killall -KILL.  So probably we need a better way to break the program when it's stuck, like if a second signal comes in while trying to deal with the first just panic.

**Comment by adiabat** [comment] 2020-01-22 15:03
ok fixed in af4ee15cecc7338e55f36b0066be3f25880b29fd with 2 bytes added...

**Comment by adiabat** [comment] 2020-01-22 15:03
(ok I guess it was 3 bytes because of the space)

**Closed by adiabat** 2020-01-22 15:03 UTC
